### ISSUE TITLE
Problem: components.misc_pkgs.openldap is not idempotent

### ISSUE THREAD

**Issue by 83bhp** [Seagate/cortx-prvsnr#40]
OpenLDAP installation fails if it is executed for the second time after first successful execution. The failure makes debugging of the following provisioner code more complicated than it should be.

`cluster.sls`:
```
cluster:
  type: single        # single/ees/ecs
  node_list:
    - eosnode-1
  eosnode-1:
    hostname: smc19-m10
    is_primary: true
    network:
      mgmt_if: eno1                   # Management network interfaces for bonding
      data_if: bond0                  # Management network interfaces for bonding
      gateway_ip:                     # No Implementation
    storage:
      metadata_device:                # Device for /var/mero and possibly SWAP
        - /dev/mapper/mpathn
      data_devices:                   # Data device/LUN from storage enclosure
        - /dev/mapper/mpatho
        - /dev/mapper/mpathb
        - /dev/mapper/mpathc
        - /dev/mapper/mpathd
        - /dev/mapper/mpathe
        - /dev/mapper/mpathf
        - /dev/mapper/mpathg
  storage_enclosure:
    id: storage_node_1            # equivalent to fqdn for server node
    type: 5U84                    # Type of enclosure. E.g. 5U84/PODS
    controller:
      type: gallium               # Type of controller on storage node. E.g. gallium/indium/sati
      primary_mc:
        ip: 127.0.0.1
        port: 8090
      secondary_mc:
        ip: 127.0.0.1
        port: 8090
      user: user
      password: 'passwd'
```

Versions:
```
> rpm -qi eos-prvsnr
Name        : eos-prvsnr
Version     : 1.0.0
Release     : 99_gitdcaf701_el7
Architecture: x86_64
Install Date: 2020-02-13T10:19:05 UTC
Group       : Tools
Size        : 524966
License     : Seagate
Signature   : (none)
Source RPM  : eos-prvsnr-1.0.0-99_gitdcaf701_el7.src.rpm
Build Date  : 2020-02-13T06:37:21 UTC
Build Host  : 4433bda62fc4
Relocations : (not relocatable)
URL         : http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr
Summary     : EOS Provisioning.
Description :
EOS Provisioning to deploy EOS Object storage software.
```
```
> rpm -qi eos-prvsnr-cli
Name        : eos-prvsnr-cli
Version     : 1.0.0
Release     : 99_gitdcaf701_el7
Architecture: x86_64
Install Date: 2020-02-13T10:16:33 UTC
Group       : Tools
Size        : 189956
License     : Seagate
Signature   : (none)
Source RPM  : eos-prvsnr-cli-1.0.0-99_gitdcaf701_el7.src.rpm
Build Date  : 2020-02-13T06:37:23 UTC
Build Host  : 4433bda62fc4
Relocations : (not relocatable)
URL         : http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr
Summary     : EOS Provisioner Command line interface.
Description :
EOS Provisioner Command line interface. Provides utilities to deploy EOS Object storage.
```
[Logs for the first run](/uploads/604ab4bccd5d01b97c81dd9a2158dafb/first_run.txt)

[Logs from the second run](/uploads/e597b4d65db7ab1c9342d9ccd1181381/second_run.txt)
