### ISSUE TITLE
Problem: concrete build id is not persisted

### ISSUE THREAD

**Issue by vvv** [Seagate/cortx-prvsnr#54]
Sequence of events:
1. Developer starts to provision the cluster in accordance with the [dual-node setup procedure][].
   `last_successful` release tag is used (default); it points at build id **B1** (e.g., 941).
2. `salt \* state.apply components.<cid>` command of `deploy-eos` script fails.
   The \<cid\> (component id) value here is either `s3server` or `hare` (their rpms depend
   on `eoscore` rpm).
3. `last_successful`, being volatile, gets updated.  Now it points at build id **B2** > **B1**.
4. Developer runs `salt \* state.apply components.<cid>.teardown`.  This uninstalls rpm(s)
   of the \<cid\> component.
5. Developer runs `salt \* state.apply components.<cid>`.
   The command fails, the error message says something about conflicting rpm versions.

`last_successful` is a symbolic link to \<build-number\> directory.
This **symbolic link is volatile**, it can be updated at any moment.
Yet it is the only reference (to build id) [persisted by Provisioner][release.sls]:
```yaml
eos_release:
    target_build: integration/centos-7.7.1908/last_successful/
    update:
        mount_base_dir: /opt/seagate/eos/updates
        repos: {}  # dictionary with (release, source) pairs
```
For installs to be reproducible, Provisioner must persist concrete build id (integer),
not the volatile tag.

**Solution:** use concrete build number (integer) in the ‘target_build’ value of
[`release.sls`][release.sls] file instead of “last_successful” tag.

[dual-node setup procedure]: http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/wikis/Setup-Guides/QuickStart-Guide#dual-node-setup-on-hardware
[release.sls]: http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/blob/master/pillar/components/release.sls
